apiVersion: v1
kind: Service
metadata:
  name: sedaro-nano-backend-svc
  labels:
    app: sedaro-nano
    tier: backend
spec:
  selector:
    app: sedaro-nano
    tier: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
