name: Destroy AWS Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout code

jobs:
  destroy:
    name: Destroy AWS Infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::047142614703:role/sedaro-nano-github-actions-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Refresh
        working-directory: ./terraform
        run: terraform refresh

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve
